### ISSUE TITLE
Will not launch on XBMC4Xbox 3.6-DEV r33032

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [divingmule/script.ircchat#9]
I got it launching a while back but now it doesn't do anything. I know it's an old Kodi version it's based on but I want to get this working to interface with ReAOL. Python errors out not being able to launch the python script. 

I have no idea which one it's erroring out on.

**Comment by divingmule** [comment]
You are going to need to find the xbmc.log file and see if there is any info printed when you try and launch the script. I can try and help if you want to paste it on pastebin.com or similar.

**Comment by RetroSoftwareRepository** [comment]
Where would you find the log file exactly?

**Comment by RetroSoftwareRepository** [comment]
08:57:47 M: 56598528  NOTICE: -----------------------------------------------------------------------
08:57:47 M: 56578048  NOTICE: Starting XBMC4Xbox 3.6-DEV-r33032 (SVN:33032, compiler 1310). Built on Feb  4 2019
08:57:47 M: 56578048  NOTICE: special://xbmc/ is mapped to: Q:\
08:57:47 M: 56578048  NOTICE: special://masterprofile/ is mapped to: Q:\UserData
08:57:47 M: 56578048  NOTICE: special://home/ is mapped to: Q:\
08:57:47 M: 56578048  NOTICE: special://temp/ is mapped to: Z:\
08:57:47 M: 56578048  NOTICE: The executable running is: C:\Dashboard\Default.xbe
08:57:47 M: 56578048  NOTICE: Log File is located: Q:\xbmc.log
08:57:47 M: 56578048  NOTICE: -----------------------------------------------------------------------
08:57:47 M: 56578048  NOTICE: Unmapped drive T
08:57:47 M: 56578048  NOTICE: Mapping drive T to Harddisk0\Partition2\Dashboard\UserData\
08:57:47 M: 56578048  NOTICE: Setup DirectX
08:57:47 M: 56549376  NOTICE: Mapping drive C to Harddisk0\Partition2
08:57:47 M: 56549376  NOTICE: Mapping drive E to Harddisk0\Partition1
08:57:47 M: 56549376  NOTICE: Unmapped drive D
08:57:47 M: 56549376  NOTICE: Mapping drive D to Cdrom0
08:57:50 M: 56549376  NOTICE:   map extended drive F:
08:57:50 M: 56549376  NOTICE: Mapping drive F to Harddisk0\Partition6
08:57:50 M: 56549376  NOTICE: Mapping drive X to Harddisk0\Partition3
08:57:50 M: 56549376  NOTICE: Mapping drive Y to Harddisk0\Partition4
08:57:50 M: 56549376  NOTICE: Unmapped drive Z
08:57:50 M: 56549376  NOTICE: Mapping drive Z to Harddisk0\Partition5
08:57:50 M: 56549376  NOTICE: load settings...
08:57:50 M: 56549376  NOTICE: Mapping drive P to Harddisk0\Partition2\Dashboard\UserData\
08:57:50 M: 56549376  NOTICE: special://profile/ is mapped to: special://masterprofile/
08:57:50 M: 56549376  NOTICE: loading special://masterprofile/guisettings.xml
08:57:50 M: 56217600  NOTICE: Getting hardware information now...
08:57:50 M: 56217600  NOTICE: Checking resolution 10
08:57:50 M: 56217600  NOTICE: Setting autoresolution mode 0
08:57:50 M: 56217600  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
08:57:50 M: 56197120  NOTICE: Loaded playercorefactory configuration
08:57:50 M: 56176640  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
08:57:50 M: 56176640  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
08:57:50 M: 56176640  NOTICE: No advancedsettings.xml to load (special://masterprofile/advancedsettings.xml)
08:57:50 M: 56176640  NOTICE: Default Video Player: dvdplayer
08:57:50 M: 56176640  NOTICE: Default Audio Player: paplayer
08:57:50 M: 56176640  NOTICE: Per AV pack settings are off
08:57:50 M: 56455168  NOTICE: special://masterprofile/sources.xml
08:57:50 M: 33021952  NOTICE: Network: Using DHCP IP settings
08:57:50 M: 32706560  NOTICE: Using idle thread with HLT (power saving)
08:57:50 M: 32694272  NOTICE: Checking the Date!
08:57:50 M: 32694272  NOTICE: start dvd mediatype detection
08:57:50 M: 32628736  NOTICE: initializing playlistplayer
08:57:50 M: 32628736  NOTICE: DONE initializing playlistplayer
08:57:50 M: 32628736  NOTICE: setting fanspeed
08:57:51 M: 32620544  NOTICE: load default skin:[XBMC Origins UI Update Mod]
08:57:51 M: 24596480  NOTICE: initialize done
08:57:51 M: 24576000  NOTICE: Running the application...
08:57:54 M: 24850432  NOTICE: start timeserver client
08:57:54 M: 24764416  NOTICE: XBFileZilla: Starting...
08:57:54 M: 24698880  NOTICE: ES: Starting event server
08:57:54 M: 24174592  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
08:57:54 M: 24174592  NOTICE: UDP: Listening on port 9777
08:57:54 M: 23511040  NOTICE: XBFileZilla: Started
08:58:07 M: 18321408  NOTICE: -->Python Initialized<--
08:58:08 M: 14299136  NOTICE: || ScriptContentFeatured::FetchLibraryData--> QueryProgramDatabase(SELECT+%2A+FROM+files+WHERE+strFileName+LIKE+%22F%3A%5CGames%5C%25%22+ORDER+BY+RANDOM%28%29+LIMIT+10)
08:58:08 M: 14229504   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\MADDEN 06\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:11 M: 21585920   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\Lego STAR WARS\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:15 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\NCAA MVP BASEBALL 06\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:19 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\Madden NFL 2004\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:23 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\NBALIVE06\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:27 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\NBA Jam\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:31 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\MVP Baseball 2005\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:35 M: 21594112   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\Rollercoaster Tycoon\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:39 M: 22118400   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\WWE WRESTLEMANIA 21\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:43 M: 22118400   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\NFL STREET\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:47 M: 22118400   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\MADDEN 06\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:51 M: 22118400   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\Lego STAR WARS\_RESOURCES\ARTWORK\thumb.jpg
Previous line repeats 1 times.
08:58:55 M: 22118400   ERROR: CGUITextureManager::Load - Texture manager unable to load file: F:\Games\NCAA MVP BASEBALL 06\_RESOURCES\ARTWORK\thumb.jpg
08:59:18 M: 20692992 WARNING: old getenv from python.lib called, library check needed
Previous line repeats 3 times.
08:59:33 M: 19546112 WARNING: JpegIO: Error 55: Not a JPEG file: starts with 0x%02x 0x%02x
08:59:35 M: 14315520  NOTICE: -->Python Initialized<--
08:59:35 M: 12591104   ERROR: Error Type: <type 'exceptions.ImportError'>
08:59:35 M: 12611584   ERROR: Error Contents: No module named xbmcaddon
08:59:35 M: 12611584   ERROR: Traceback (most recent call last):
                                              File "Q:\scripts\IrcChat\default.py", line 10, in <module>
                                                import xbmcaddon
                                            ImportError: No module named xbmcaddon

**Comment by RetroSoftwareRepository** [comment]
Here's the section that didn't get copied from the log that is why Python is getting hung up: 08:59:35 M: 14315520  NOTICE: -->Python Initialized<--
08:59:35 M: 12591104   ERROR: Error Type: <type 'exceptions.ImportError'>
08:59:35 M: 12611584   ERROR: Error Contents: No module named xbmcaddon
08:59:35 M: 12611584   ERROR: Traceback (most recent call last):
                                              File "Q:\scripts\IrcChat\default.py", line 10, in <module>
                                                import xbmcaddon
                                            ImportError: No module named xbmcaddon

**Comment by divingmule** [comment]
Something seems to be a miss with your installation. The error _No module named xbmcaddon_ seems to indicate you don't have the xbmcaddon python module. It's a built-in module that comes with xbmc -> https://kodi.wiki/view/Python_libraries.

I don't know if there is anything different you have to do for XBMC4Xbox but... I was looking at these add-ons here -> https://github.com/noobsandnerds/addons4xbox  and they all use the xbmcaddon module also, so it doesn't seem so.

Sorry, I don't know what else to tell you.

**Comment by RetroSoftwareRepository** [comment]
> Something seems to be a miss with your installation. The error _No module named xbmcaddon_ seems to indicate you don't have the xbmcaddon python module. It's a built-in module that comes with xbmc -> https://kodi.wiki/view/Python_libraries.
> 
> 
> 
> I don't know if there is anything different you have to do for XBMC4Xbox but... I was looking at these add-ons here -> https://github.com/noobsandnerds/addons4xbox  and they all use the xbmcaddon module also, so it doesn't seem so.
> 
> 
> 
> Sorry, I don't know what else to tell you.

It works now, but just like when I originally ran it... it doesn't function to connect to an IRC server. 
System used:
Original Xbox running XBMC4Xbox 3.6-DEV (r33032)
(Fixed dependency issues so it now runs)
